name: Mini E-Commerce CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./mini-ecommerce

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Give permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Compile Application
        run: ./mvnw clean compile

      - name: Run Tests
        run: ./mvnw test

      - name: Build Application
        run: ./mvnw package